default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  user: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: Reserva-de-Salas_development

test: &test
  <<: *default
  database: Reserva-de-Salas_test

production:
  <<: *default
  database: Reserva-de-Salas_production
  username: Reserva-de-Salas
  password: <%= ENV['RESERVA-DE-SALAS_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
